#! /bin/sh

DOM=${1}
CORE=${2}
CYC=${3}
DATE=${4}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi



module load prod_envir
module load prod_util

cd /lfs/h2/emc/lam/noscrub/Matthew.Pyle/hiresw.v8.1.0/launch_info/


echo NDATE is $NDATE



if [ $DOM$CORE == "hiarw" ] 
then
MODPROCS=82
MODSPAN=82
MODNODES=1
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "himem2arw" ]
then
MODPROCS=82
MODSPAN=82
MODNODES=1
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "prarw" ]
then
MODPROCS=158
MODNODES=2
MODSPAN=79
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "prmem2arw" ]
then
MODPROCS=124
MODNODES=1
MODSPAN=124
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "guamarw" ]
then
MODPROCS=104
MODNODES=1
NCPUSMOD=100
NCPUSQUILT=4
MODSPAN=104
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "conusarw" ]
then
MODPROCS=1632
MODNODES=12
NCPUSMOD=128
NCPUSQUILT=96
MODSPAN=128
POSTPROCS=22
POSTSPAN=11
PRDGENPROCS=13
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
elif [ $DOM$CORE == "conusmem2arw" ]
then
MODPROCS=1376
MODNODES=10
NCPUSMOD=128
NCPUSQUILT=96
MODSPAN=128
POSTPROCS=16
POSTSPAN=8
PRDGENPROCS=12
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
elif [ $DOM$CORE == "akarw" ]
then
MODPROCS=1340
MODNODES=10
MODSPAN=128
NCPUSMOD=128
NCPUSQUILT=60
POSTPROCS=16
POSTSPAN=8
PRDGENPROCS=5
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
elif [ $DOM$CORE == "akmem2arw" ]
then
MODPROCS=944
NCPUSMOD=128
MODNODES=7
NCPUSQUILT=48
MODSPAN=24
POSTPROCS=16
POSTSPAN=8
PRDGENPROCS=5
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
fi

cat ungrib.lsf_in_cray_offset_retro | sed s:_DATE_:${DATE}:g | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_ungrib.lsf_${DOM}_${CORE}_${CYC}_retro

cat metgrid.lsf_in_cray_retro |  sed s:_DATE_:${DATE}:g | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_metgrid.lsf_${DOM}_${CORE}_${CYC}_retro


if [ $CORE == "nmmb" ]
then

cat sub_nemsinterp_1.lsf_in_cray_retro |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_nemsinterp_1.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_nemsinterp_2.lsf_in_cray_retro |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_nemsinterp_2.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_nemsinterp_3.lsf_in_cray_retro |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_nemsinterp_3.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_nemsinterp_4.lsf_in_cray_retro |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_nemsinterp_4.lsf_${DOM}_${CORE}_${CYC}_retro

cat prelim.lsf_bigrap_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_preprap.lsf_${DOM}_${CORE}_${CYC}_retro

else

cat prelimfinal.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_prelimfinal.lsf_${DOM}_${CORE}_${CYC}_retro

cat prelim.lsf_bigrap_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_DATE_:${DATE}:g | sed s:_CYC_:${CYC}:g > sub_preprap.lsf_${DOM}_${CORE}_${CYC}_retro

fi

if [ $DOM == "conus" -o $DOM == "ak" -o $DOM == "conusmem2" -o $DOM == "akmem2" ]
then
cat sub_model.lsf_in_cray_retro_big | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_SPAN_:${MODSPAN}:g | sed s:_NODES_:${MODNODES}:g | sed s:_NPROC_:${MODPROCS}:g | \
sed s:_NCPUSMOD_:${NCPUSMOD}:g | sed s:_NCPUSQUILT_:${NCPUSQUILT}:g > sub_model.lsf_${DOM}_${CORE}_${CYC}_retro


else

cat sub_model.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_SPAN_:${MODSPAN}:g | sed s:_NODES_:${MODNODES}:g | sed s:_NPROC_:${MODPROCS}:g  > sub_model.lsf_${DOM}_${CORE}_${CYC}_retro

fi

cat sub_post.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_POSTSPAN_:${POSTSPAN}:g |  sed s:_NPROC_:${POSTPROCS}:g  > sub_post.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_postodd.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_POSTSPAN_:${POSTSPAN}:g |  sed s:_NPROC_:${POSTPROCS}:g  > sub_postodd.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_posteven.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_POSTSPAN_:${POSTSPAN}:g |  sed s:_NPROC_:${POSTPROCS}:g  > sub_posteven.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_prdgen.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_SPAN_:${PRDGENSPAN}:g |  sed s:_NPROC_:${PRDGENPROCS}:g  > sub_prdgen.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_wrfbufrsnd.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g |  sed s:_PTILEBUFR_:${BUFRSPAN}:g |  sed s:_NPROCBUFR_:${NPROCBUFR}:g  > sub_wrfbufrsnd.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_smartinit.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g > sub_smartinit.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_smartinitb.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
sed s:_DATE_:${DATE}:g > sub_smartinitb.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_awips.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
      sed s:_DATE_:${DATE}:g > sub_awips.lsf_${DOM}_${CORE}_${CYC}_retro

cat sub_gempak.lsf_in_cray_retro | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
      sed s:_DATE_:${DATE}:g > sub_gempak.lsf_${DOM}_${CORE}_${CYC}_retro



# qsub sub_ungrib.lsf_${DOM}_${CORE}_${CYC}_retro

if [ $DOM == "conus" -o $DOM == "pr" ]
then
# qsub sub_preprap.lsf_${DOM}_${CORE}_${CYC}_retro
echo nosubmit
fi
