#!/bin/sh

########################################
# RUNS HIRESW POST MANAGER JOB
########################################
set -xa
export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
export POST_DATA=${DATA:-${DATAROOT:?}/hiresw.post_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
export PRDGEN_DATA=${DATA:-${DATAROOT:?}/hiresw.prdgen_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
mkdir -m 775 -p $DATA $POST_DATA $PRDGEN_DATA

export INPUT_DATA=${INPUT_DATA:-${DATAROOT:?}/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}

####################################
# Run setpdy and initialize PDY variables
####################################

export cycle=${cycle:-t${cyc}z}
cd ${POST_DATA}
setpdy.sh
. ./PDY
cd ${PRDGEN_DATA}
setpdy.sh
. ./PDY
cd $DATA
setpdy.sh
. ./PDY

export HOMEhiresw=${HOMEhiresw:-${PACKAGEROOT:?}/hiresw.${hiresw_ver:?}}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

export pgmout="OUTPUT.$$"

########################################################
# Run the ex-script
#

${HOMEhiresw}/scripts/${MODEL}/exhiresw_pmgr.sh

export err=$?

#
########################################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

postmsg  "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
